### ISSUE TITLE
Replicating the training in my environment

### ISSUE THREAD

**Issue by neerajsangal** [conan-io/training#1]
I was able to get the training to work in the tutorial provided environment. Now I am trying to do it in my environment. My Azure Ubuntu has:

- gcc 7.4.0
- conan 1.18.4
- cmake 3.10.2

When I run the command "conan install .." from consumer/build, it finds and installs the packages boost, pocoproject, and their dependencies. However, it asks me to log into conan-center. As per the suggestions, I created an account in https://bintray.com/signup/oss.

However, when I  specify my user name and password, it tells me that the password is wrong. As a result, conanbuildinfo.cmake is not generated.  Any help is appreciated.

**Comment by memsharded** [comment]
Hi @neerajsangal 

There has been a release of the urllib dependency that broke Conan (check https://github.com/conan-io/conan/issues/5784). Please try updating to latest Conan 1.18.5 release, that will exclude that broken dependency, and make sure to install cleanly again. Let me know if it works, thanks!

**Comment by neerajsangal** [comment]
Thanks. The "conan install .." command completes now, the packages are installed and the conanbuildinfo.cmake and other files are generated. 

However, when I try to build the bin/timer(the first exercise), I get an undefined reference. Not sure how that can be because the tutorial specifies a specific version of boost (1.67.0) and boost package was successfully installed. Here is the error:

neeraj@Ubuntu:~/training/consumer/build$ cmake --build .
Scanning dependencies of target timer
[ 50%] Building CXX object CMakeFiles/timer.dir/timer.cpp.o
[100%] Linking CXX executable bin/timer
...
timer.cpp:(.text._ZN5boost16re_detail_10670012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE22unwind_long_set_repeatEb[_ZN5boost16re_detail_10670012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE22unwind_long_set_repeatEb]+0x706): undefined reference to `boost::re_detail_106700::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
...
collect2: error: ld returned 1 exit status
CMakeFiles/timer.dir/build.make:94: recipe for target 'bin/timer' failed
make[2]: *** [bin/timer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/timer.dir/all' failed
make[1]: *** [CMakeFiles/timer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by memsharded** [comment]
Hi @neerajsangal 

It seems you are using a different libcxx in your build and in the default profile. Try to change the profile to ``compiler.libcxx=libstdc++11`` if that is your compiler default, and repeat. Is it possible that in the orbitera environment the default profile was already adjusted.

**Comment by neerajsangal** [comment]
Thanks, that was exactly the problem. I will continue with the tutorial in my environment. This is what my profile/default looks like:

**Comment by memsharded** [comment]
Cool!
Yes, indeed that default is something that we want to change, but we cannot now without breaking the world, we will need to wait until Conan 2.0. 
Thanks for the feedback, going to close this issue now, don't hesitate to open new ones as necessary.
