### ISSUE TITLE
Cannot load zlib/1.2.13 recipe for first exercise

### ISSUE THREAD

**Issue by s-ker-s** [conan-io/training#106]
The `conan install` step for the first exercise doesn't work for me in the provided docker container due to zlib/1.2.13 depending on conan >= 1.53.0 (see log below).

Executing `pip install --force-reinstall conan` in the container did the trick for me (installs conan 1.54.0).

````
conan@d937df890489:~/training/consumer/build$ conan install ..
WARN: Remotes registry file missing, creating default one in /home/conan/.conan/remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

boost/1.72.0: Not found in local cache, looking in remotes...
boost/1.72.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [1.35k]                                          
Downloading conanfile.py completed [80.82k]                                              
Downloading conan_export.tgz completed [1.48k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
boost/1.72.0: Downloaded recipe revision 0
zlib/1.2.13: Not found in local cache, looking in remotes...
zlib/1.2.13: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.28k]                                          
Downloading conanfile.py completed [4.04k]                                               
Downloading conan_export.tgz completed [0.29k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
zlib/1.2.13: Downloaded recipe revision 0
ERROR: zlib/1.2.13: Cannot load recipe.
Error loading conanfile at '/home/conan/.conan/data/zlib/1.2.13/_/_/export/conanfile.py': Current Conan version (1.52.0) does not satisfy the defined one (>=1.53.0).
````

**Comment by memsharded** [comment]
Hi @s-ker-s 

Thanks very much for reporting. It seems that with the high activity that is now around ConanCenter to prepare for Conan 2.0, recipes are changing quickly, requiring using latest Conan. We will update the docker image, in the meantime, can you please try with a ``pip install conan --upgrade`` inside the docker instance and retry? (you can also do a ``conan remove "*" -f`` to clean from your cache previous recipes if necessary)

**Comment by memsharded** [comment]
I have updated the docker images and course catchup.sh. Please use that as a reference, some parts of the videos might be outdated (zlib/1.2.11 now is zlib/1.2.13, the cross compiler version 7 is now 9)

You might need to clean your docker container and image and re-build it from scratch, please ask for help if you need it. 

I am closing this issue as solved, thanks!

**Comment by s-ker-s** [comment]
Great, thanks for the quick fix!
