### ISSUE TITLE
Connecting to Artifactory 

### ISSUE THREAD

**Issue by neerajsangal** [conan-io/training#2]
To mimic the tutorial, I created a repo in JFrog bintray (https://bintray.com/nsangal/myconanrepo) and I would like to upload the hello package as per the tutorial.

However, I get log in error - Wrong user or password.

neeraj@Ubuntu:~/training$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
artifactory: https://api.bintray.com/conan/nsangal/myconanrepo [Verify SSL: True]

neeraj@VerifaNeerajUbuntu:~/training$ conan upload "hello" -r artifactory --all
Are you sure you want to upload 'hello/0.1@user/testing' to 'artifactory'? (yes/no): yes
Uploading to remote 'artifactory':
Uploading hello/0.1@user/testing to remote 'artifactory'
Please log in to "artifactory" to perform this action. Execute "conan user" command.
If you don't have an account sign up here: https://bintray.com/signup/oss
Remote 'artifactory' username: nsangal
Please enter a password for "nsangal" account:
ERROR: Wrong user or password

I typed the user and password that I use to log into the JFrog bintray account. Thanks for your help.

**Comment by neerajsangal** [comment]
It worked when I used the Apikey and then did the upload.

$ conan user -p <APIKEY> -r myrepo nsangal

Closing the issue.

**Comment by memsharded** [comment]
Yes, exactly, Bintray works with the API Key, not password.

To try things, I would also recommend also to download a free Artifactory CE and run it locally, it is easy, and you will keep your packages private too.
