### ISSUE TITLE
FreeTier migration issue: Please use a local ArtifactoryCE instance for the training

### ISSUE THREAD

**Issue by memsharded** [conan-io/training#42]
The recommended Free Trier is under a migration issue right now.

It is strongly recommended to grab the ArtifactoryCE from https://conan.io/downloads.html (for training purposes, getting the .zip or .tgz, unzipping and running the script in app/bin, then going to <IP>:8082 will be good). 

The training shouldn't be affected, just taking care to use the real <IP>, instead of localhost can avoid issues connecting from the docker container.

**Comment by solvingj** [comment]
The slides and videos and instructions in Jfrog academy have been updated to use artifactory CE local.
