### ISSUE TITLE
Consuming Conan Package 8/9 question typo

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/training#53]
I'm following the [Conan essential track](https://academy.jfrog.com/conan-essentials/) and notice a typo in the *Consuming Conan Package* 8/9 question:

> Which commands accept the flag --html and produce novel html output?

I think the flag is `--graph`.

**Comment by solvingj** [comment]
Ah, great find!  I believe that `--html` was the flag in a previous version and it has ben changed. Indeed, `conan info` accepts `--graph` and also can produce `html` or `dot` output, but I chose `conan search` as the command to focus on.

I have changed the question to: 

`Which command accepts the flag --table and produces html output?`

and the answer is `conan search`
