### ISSUE TITLE
Strange behavior when completing last essential path quizz

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/training#55]
The quizz which is rather a satisfaction inquiry is failing upon a satisfied submission:
![Screenshot 2020-10-15 at 15 06 00](https://user-images.githubusercontent.com/879889/96138470-18790b00-0efe-11eb-88a2-946c037e0334.png)

**Comment by solvingj** [comment]
Thank you for reporting this, someone just reported it yesterday and we're going to fix it ASAP.

**Comment by EMCP** [comment]
+1, glad to hear it's getting looked into.  great course and intro though!

**Comment by solvingj** [comment]
The course completion has been fixed and converted to a proper survey.  Thanks so much for the feedback.
