### ISSUE TITLE
[Feedback] Move the question about user/channel to section "Create Conan Packages"

### ISSUE THREAD

**Issue by j-silver** [conan-io/training#56]
The quiz at the end of the section _Consuming Conan Packages_ contains a question about whether users should populate the attributes _user_ and _channel_ when building locally. However, I couldn't find any reference to this advice in the section. I wonder whether this question should actually belong to the section _Create Conan Packages_

**Comment by solvingj** [comment]
Thank you for reporting, looking into it now.

**Comment by solvingj** [comment]
Absolutely right, fixed/moved.
