### ISSUE TITLE
Packages published to artifactory have extra characters in name

### ISSUE THREAD

**Issue by dragondive** [conan-io/training#57]
Hello everyone,

I set up an artifactory (community edition 7.10.5) on `localhost`. I ran the following commands from the command line:

    conan new pkg/0.1@aravind/testing -s -t
    conan create .
    conan upload pkg/0.1 -r localrepo --all
    
The package is uploaded with the name `_/pkg/0.1/_`. I could not figure out where the extra characters `/` and `_` come from. What am I missing here?

<img width="320" alt="conan_upload_extra_characters" src="https://user-images.githubusercontent.com/2300602/98830532-86aee000-2460-11eb-9fa8-020e45cd2e45.png">

**Comment by memsharded** [comment]
Hi @dragondive 

You need to:

```
$ conan create . aravind/testing
$ conan upload pkg/0.1@aravind/testing-r localrepo --all
```

Otherwise you are creating a package without user/channel, and that is represented in artifactory path as "_" (as empty folders are not allowed in the path)

**Comment by solvingj** [comment]
@dragondive please let us know if this answers your question, or if we can provide further guidance.

**Comment by dragondive** [comment]
Hi @dragondive @solvingj, thanks, yes this answers my question. 
I had (mis)understood that if the user and channel weren't explicitly specified, they would be defaulted to the values chosen when creating the package with `conan new`.
