### ISSUE TITLE
Could not connect to jfrog User Interface whit https://127.0.0.1:8082

### ISSUE THREAD

**Issue by ixtrader** [conan-io/training#58]
All steps up to "Remote Repositories on Artifactory" are working fine. But in this chapter I have to setup the JFrog Conan Repository. This is not possible because while connection to https://127.0.0.1:8082 (changed) I got the response "Service Unavaliable"

Do you have an Idea whats going wrong? Containers are started

Kind Regards
Martin

F:\GitHubClones\training\docker_environment>docker container ls
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                              NAMES
954baf5fbc63        conan_training_env_conan-training               "tail -f /dev/null"      14 minutes ago      Up 5 minutes                                           conan-training
e030b0448f87        conan_training_env_jfrog-artifactory-training   "/entrypoint-artifac…"   14 minutes ago      Up 5 minutes        8081/tcp, 0.0.0.0:8082->8082/tcp   jfrog-artifactory-training

**Comment by ixtrader** [comment]
I switched form:

FROM docker.bintray.io/jfrog/artifactory-cpp-ce:7.6.2
FROM docker.bintray.io/jfrog/artifactory-cpp-ce:latest

and the Problem seems to vanish.

**Comment by solvingj** [comment]
Please try reverting back to the original artifactory URL and trying the following link instead: 

http://localhost:8082

Also, in terms of IP address, the one you provided here is incorrect:

You said : `120.0.0.1`
And it would be:  `127.0.0.1`

In either case (`localhost` or `127.0.0.1`, you need to include the port `8082`

**Comment by ixtrader** [comment]
Sorry for the mistake.
You are perfectly right. But only the post ist false. I wrote 120.0.0.1 and ment 127.0.0.1:8082.

I corrected the original post. 
But the Result is the same.

**Comment by solvingj** [comment]
Can you post the full log of the `docker-compose up` command?

**Comment by ixtrader** [comment]
FROM docker.bintray.io/jfrog/artifactory-cpp-ce:7.11.2
[startup.log](https://github.com/conan-io/training/files/5612175/startup.log)

**Comment by ixtrader** [comment]
Hello @solvingj the issue only occurs when using docker server on windows. I switched now to an CENTOS 7 and the artifactory is starting out of the box. 
Problem: Windows

**Comment by solvingj** [comment]
Can you post the version number of Docker on windows?

**Comment by ixtrader** [comment]
Docker version 19.03.13, build 4484c46d9d

**Comment by solvingj** [comment]
Thanks for the info.  The windows docker is certainly new enough you should not need to do anything special to make it work.  Several of us test on Windows so your issue is still a mystery. 

The log only shows the Artifactory startup log.  I would like to see the whole compose output log if that were possible.

**Comment by solvingj** [comment]
Sorry we were never able to find any useful guidance for your issue.  Were you able to get it working?  Would you like to continue troubleshooting?

**Comment by ixtrader** [comment]
Thank you for the question. Im am now happy with Conan. I installed the training on an real Linux instance without any Problem.

**Comment by madukan** [comment]
This issue is not just on Windows, but also on Mac too. Quite annoying. Logs, it that helps: 
[docker_log.txt](https://github.com/user-attachments/files/15520110/docker_log.txt)

Command to start JFrog docker:
```sh
JFROG_HOME="`pwd`"

docker run --rm --name artifactory -v $JFROG_HOME/artifactory/var/:/var/opt/jfrog/artifactory -d -p 8081:8081 -p 8082:8082 docker.bintray.io/jfrog/artifactory-cpp-ce:latest
```

<img width="598" alt="image" src="https://github.com/conan-io/training/assets/7971561/f8b3f1e6-c834-4a3b-9185-f80cf0044f83">

**Comment by memsharded** [comment]
Hi @madukan 

I don't know if you have seen the warnings, both in the repo and in the JFrog Academy.

This training is completely outdated. It is expected that instructions and commands will fail. This repo is still visible mostly for historic reasons, same as the Academy videos.

**Comment by madukan** [comment]
Hi @memsharded 
I noticed this was from a training program. I just listed the issue as that was happening from the standard instructions from the JFrog Wiki as well! Couldn't get it solved, so flagged with the most similar issue I could find during that time.
Is there a better way to report this matter and get it addressed at all?
Thanks for your response.

**Comment by memsharded** [comment]
For typical Conan client issues the repo would be: https://github.com/conan-io/conan

If this about running Artifactory the instructions are in the downloads page: https://conan.io/downloads

If there is something to fix in this site, like the instructions to run Artifactory, then the place is https://github.com/conan-io/web

If the instructions come from https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes/artifactory/artifactory_ce_cpp.html#artifactory-ce-cpp, then the repo is https://github.com/conan-io/docs

The instructions in the download page are:

> docker run --name artifactory -d -p 8081:8081 -p 8082:8082 releases-docker.jfrog.io/jfrog/artifactory-cpp-ce:latest


As you can see this is not the same as the one you are using, that likely comes from the training, as said, the training is outdated and broken.

**Comment by madukan** [comment]
I was trying to run on both Linux and Mac environments. Issue is the same on both. Quite strange!

```
docker run --name artifactory -d -p 8081:8081 -p 8082:8082 releases-docker.jfrog.io/jfrog/artifactory-cpp-ce:latest
```

Logs:
```
2024-06-03 07:20:05 2024-06-02T21:20:05.348Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory, attempt number 60
2024-06-03 07:20:05 2024-06-02T21:20:05.355Z [jffe ] [INFO ] [] [frontend-service.log] [main                ] - pinging artifactory attempt number 60 failed with code : ECONNREFUSED
2024-06-03 07:20:09 2024-06-02T21:20:09.781Z [jfrou] [INFO ] [25c745b27f92eb83] [security_keys.go:172          ] [main                ] [] - Master key is missing. Pending for 65 seconds with 5m0s timeout
2024-06-03 07:20:09 2024-06-02T21:20:09.783Z [jfmd ] [INFO ] [                ] [security_keys.go:172          ] [main                ] - Master key is missing. Pending for 65 seconds with 2m0s timeout [init]
2024-06-03 07:20:09 2024-06-02T21:20:09.856Z [jfevt] [INFO ] [610a85290ebf4536] [security_keys.go:172          ] [main                ] [                ] - Master key is missing. Pending for 65 seconds with 2m0s timeout [startup]
2024-06-03 07:20:10 2024-06-02T21:20:10.012Z 35[jfob ] [INFO ] [16ab3bed9442eaa1] [security_keys.go:172          ] [main                ] - Master key is missing. Pending for 65 seconds with 2m0s timeout [startup]
```

**Comment by memsharded** [comment]
Ok, it seems the ``latest`` which is some kind of link is broken. It should work with a explicit version:
```
docker run --name artifactory -p 8081:8081 -p 8082:8082 releases-docker.jfrog.io/jfrog/artifactory-cpp-ce:7.77.5
```
(I have removed the ``-d`` for seeing errors)

**Comment by memsharded** [comment]
(we are having a look to fix the ``latest``, but at least you have a workaround to move forward)

**Comment by madukan** [comment]
Thank you for that. The `artifactory-cpp-ce:7.77.5` worked fine. Might be a link broken like you say in the `latest`. 
Much appreciated you looking into this.

**Comment by memsharded** [comment]
I have created a new ticket in https://github.com/conan-io/conan/issues/16411, assigned for next release, so we can track and try to fix it soon.

**Comment by madukan** [comment]
That sounds perfect. Thanks again.
