### ISSUE TITLE
[Conan Essentials] Docker Compose Fails

### ISSUE THREAD

**Issue by godsmith99x** [conan-io/training#62]
In Conan Essentials/Environment Setup video, docker compose command fails and gives the following output:
Building jfrog-artifactory-training
Step 1/11 : FROM docker.bintray.io/jfrog/artifactory-cpp-ce:7.6.2
ERROR: Service 'jfrog-artifactory-training' failed to build : missing or empty Content-Length header

I am on docker version 20.10.1, docker-compose version 1.27.4, containerd version 1.4.3.

I edited the Docker YAML file to pull FROM docker.bintray.io/jfrog/artifactory-cpp-ce:7.12.5 and the docker image built successfully. I have not yet completed the rest of the training to ensure everything works correctly with this newer version of artifactory.

**Comment by uilianries** [comment]
Hi @godsmith99x ! This error only occurs with Docker 20.x, if you are able to run Docker 19.x that error won't occur.

**Comment by solvingj** [comment]
@godsmith99x i will push a fix for this shortly.

**Comment by godsmith99x** [comment]
Thanks!

**Comment by solvingj** [comment]
You can easily apply the patch yourself instead of waiting for the merge.  It probably won't get merged until tomorrow.
