### ISSUE TITLE
[Bug] Note : "create" command with "in-source" recipe is local - duplicated video

### ISSUE THREAD

**Issue by designerzim** [conan-io/training#79]
In the Create Conan Packages section, the entry **Note : "create" command with "in-source" recipe is local** uses the same video as the previous note: **Note : "create" and "test_package" are local**

Expected:

The image and VO in this entry would reference "in-source"

Actual:

The image and VO reference "test_package"

It seems probable that one can infer this means the same practical thing for "in-source" as it does for "test_package" but it does leave things a little confused.

**Comment by solvingj** [comment]
I just reviewed the lesson, and it seems that there really was not supposed to be a unique note/lesson/video here. It was an erroneously named duplicate that nobody has noticed or reported until now. I have removed the duplicated video.
