### ISSUE TITLE
[Bug] Exercise : Upload to Artifactory - Part 1 - video end frame is not useful

### ISSUE THREAD

**Issue by designerzim** [conan-io/training#81]
The end of an exercise video normally shows the list of commands needed for the exercise: very helpful.

This video ends showing the first slide (if not frame). The outline for the exercise is shown, and does not include any commands.

This requires users to pause the video on the commands to keep the reference up and is different behavior from the previous exercise videos.

Ignoring the 12 web UI instructions (as well as missing instructions to get to that UI described in #80), there is only one command not on the final slide. This first command is simple enough (as well as optional) so that the larger list of commands from the final slide alone would be helpful enough to keep displayed at video's end.

**Comment by solvingj** [comment]
I have updated the "video end frame". Please let me know if it looks good now.
