### ISSUE TITLE
upload failed: wrong ssl version number, despite Verify SSL: False

### ISSUE THREAD

**Issue by tantal92** [conan-io/training#90]
Cource: Advanced, Exercise : Revisions - Part 2

```
hello/0.1@user/testing: Upload recipe to 'artifactory' failed: HTTPSConnectionPool(host='127.0.0.1', port=8082):   
Max retries  exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER]   
wrong version number  (_ssl.c:1131)')))

Unable to connect to artifactory=https://127.0.0.1:8082
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

ERROR: Errors uploading some packages
```

output of netcat:
```
nc -zv 127.0.0.1 8082
Connection to 127.0.0.1 8082 port [tcp/*] succeeded!
```

```
conan remote list
artifactory: https://127.0.0.1:8082 [Verify SSL: False]
```

**Comment by memsharded** [comment]
Hi @tantal92 

Quick question, is this something that only happen in the Advanced course? How did you manage to finish the Basics course, did it worked then, and now it is failing? Can you type ``conan --version`` in the environment, just to make sure too of the Conan version?

**Comment by tantal92** [comment]
Hi,
I finished basic course about 1 year ago;
that time I also had some problems with connection (unfortunately I don't remember if it was the same), but changing image tag to `latest` in `artifactory-training/Dockerfile`, as in this Issue:
https://github.com/conan-io/training/issues/58#issuecomment-734881127

solved that problem that time

**Comment by tantal92** [comment]
@memsharded 
sorry, I forgot to provide conan version: 
```
Conan version 1.40.3
```

**Comment by memsharded** [comment]
Yes, that seems the issue. Need to upgrade to Conan 1.43, the latest training docker would do that, you need to upgrade.

**Comment by tantal92** [comment]
updated to latest conan 1.42.2 (1.43 is probably not released yet? )
this time I used dns adress from docker-compose network:

conan --version
`conan version 1.42.2`
conan remote add artifactory https://jfrog-artifactory-training:8082
conan upload 'hello*' --all -r=artifactory --confirm

```
ERROR: hello/0.1@user/testing: Upload recipe to 'artifactory' failed:   
HTTPSConnectionPool(host='jfrog-artifactory-training', port=8082): Max retries exceeded with url: /v1/ping  
 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')))

Unable to connect to artifactory=https://jfrog-artifactory-training:8082
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

ERROR: Errors uploading some packages
```

same result with disabled ssl:
`artifactory: https://jfrog-artifactory-training:8082 [Verify SSL: False]`

**Comment by memsharded** [comment]
Hi @tantal92 

You are right, latest Conan released is 1.42.2.

Regarding your remote, I think you are adding it wrong. If you recall the "Basic" training, you need to add the ``SetMeUp`` button URL, not the web ui URL. It should look more like ``https://...../artifactory/api/conan/conan-local``

**Comment by tantal92** [comment]
Ohh, I'm sorry, you're right!
I forgot about that :( Now it's working.
I'm closing this Issue.

Thank you very much for your support!

**Comment by memsharded** [comment]
Happy to help! 😄
