### ISSUE TITLE
Conan Essentials - Consuming Conan Packages - Incorrect "conancenter" Search Remote Option

### ISSUE THREAD

**Issue by Narwhalrus** [conan-io/training#99]
In the Conan Essentials->Consuming Conan Packages->Features : Info and Search training segment, the `-r=conan-center` argument to conan search should instead be `-r=conancenter`

**Comment by memsharded** [comment]
Thanks @Narwhalrus 
I have updated the exercises notes to reflect this change (re-recording the video is too much, as this is actually optional, not part of the exercise).
